Feature/webpack upgrades
rijkvanzanten/obachine pull request #20
Opened 2017-06-08 12:58 UTC by Mimaaa

2017-06-08 14:19 UTC, rijkvanzanten commented on app/routes/body.css
> +.toedeledokie {
What's this, why is it here

2017-06-08 14:30 UTC, rijkvanzanten commented on records.json
> +{
what's this file? what is it for? what does it do?

2017-06-08 14:30 UTC, rijkvanzanten requested changes
Nice changes. I'm wondering what all these extra files are for?

2017-06-08 14:31 UTC, rijkvanzanten commented
Could you maybe add some documentation to this PR?

2017-06-08 20:44 UTC, rijkvanzanten commented on app/components/parts/genre/index.js
> +  title: 'Hoi dit zijn instellingen toch',
😂

2017-06-08 21:03 UTC, rijkvanzanten requested changes

2017-06-08 21:03 UTC, rijkvanzanten commented on package.json
> +    "lint:js": "eslint app/ webpack.*.js --cache",
❗️  This doesn't lint `server.js` and `api.js`

2017-06-08 21:05 UTC, Mimaaa commented on package.json
> +    "lint:js": "eslint app/ webpack.*.js --cache",
Good one.

2017-06-08 21:14 UTC, Mimaaa commented
records.json and stats.json are removed from the repo by a .gitignore.

**stats.json**
Importing the stats.json into a webpack analyser helps you understand the composition of your bundles.

**records.json**
"Records are particularly valuable if you have a complicated setup with code splitting and want to make sure the split parts gain correct caching behavior." SurviveJS - Webpack

2017-06-09 09:14 UTC, rijkvanzanten requested changes

2017-06-09 09:14 UTC, rijkvanzanten commented on .eslintrc.js
> +    'no-console': 0,
Maybe we should check for remaining console.log statements. We don't want to fill up the dev console with useless info when it isn't needed anymore

2017-06-09 09:14 UTC, rijkvanzanten commented on package.json
> +    "xo": "^0.18.2"
Do we still need this dependency when switching to `eslint` completely?

2017-06-09 10:15 UTC, rijkvanzanten approved these changes

2017-06-09 10:15 UTC, merged